# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./build -o _site
  
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.5
        with:
          path: _site/
          retention-days: 1

#       - name: Configure GitHub Pages
#         uses: actions/configure-pages@v2.1.3
#         with:
#           # GitHub token
#           token: # default is ${{ github.token }}
#           # Should a Pages site be enabled for the repository if not so already?
#           enablement: # optional, default is true

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          timeout: 60

